% Generated by rdf-prolog-roundtrip.

% RDF terms use rdf(Subject, Predicate, Object, Graph).

rdf(iri('https://example.org/consumer-policy'), iri('http://www.w3.org/ns/odrl/2/permission'), iri('https://example.org/delete-account'), default_graph).
rdf(iri('https://example.org/consumer-policy'), iri('http://www.w3.org/ns/odrl/2/permission'), iri('https://example.org/change-terms'), default_graph).
rdf(iri('https://example.org/consumer-policy'), iri('http://www.w3.org/ns/odrl/2/permission'), iri('https://example.org/share-data'), default_graph).
rdf(iri('https://example.org/consumer-policy'), iri('http://www.w3.org/ns/odrl/2/prohibition'), iri('https://example.org/export-data'), default_graph).
rdf(iri('https://example.org/consumer-policy'), iri('https://example.org/riskProfile'), iri('https://example.org/deletion-profile'), default_graph).
rdf(iri('https://example.org/consumer-policy'), iri('https://example.org/riskProfile'), iri('https://example.org/terms-profile'), default_graph).
rdf(iri('https://example.org/consumer-policy'), iri('https://example.org/riskProfile'), iri('https://example.org/sharing-profile'), default_graph).
rdf(iri('https://example.org/consumer-policy'), iri('https://example.org/riskProfile'), iri('https://example.org/portability-profile'), default_graph).
rdf(iri('https://example.org/delete-account'), iri('https://example.org/clause'), literal('c1', datatype('http://www.w3.org/2001/XMLSchema#string')), default_graph).
rdf(iri('https://example.org/delete-account'), iri('http://www.w3.org/ns/odrl/2/action'), iri('https://example.org/remove-account'), default_graph).
rdf(iri('https://example.org/change-terms'), iri('https://example.org/clause'), literal('c2', datatype('http://www.w3.org/2001/XMLSchema#string')), default_graph).
rdf(iri('https://example.org/change-terms'), iri('http://www.w3.org/ns/odrl/2/action'), iri('https://example.org/change-terms-action'), default_graph).
rdf(iri('https://example.org/change-terms'), iri('http://www.w3.org/ns/odrl/2/duty'), iri('https://example.org/inform-duty'), default_graph).
rdf(iri('https://example.org/inform-duty'), iri('http://www.w3.org/ns/odrl/2/action'), iri('https://example.org/inform'), default_graph).
rdf(iri('https://example.org/change-terms'), iri('http://www.w3.org/ns/odrl/2/constraint'), iri('https://example.org/notice-constraint'), default_graph).
rdf(iri('https://example.org/notice-constraint'), iri('http://www.w3.org/ns/odrl/2/leftOperand'), iri('https://example.org/noticeDays'), default_graph).
rdf(iri('https://example.org/notice-constraint'), iri('http://www.w3.org/ns/odrl/2/operator'), iri('http://www.w3.org/ns/odrl/2/eq'), default_graph).
rdf(iri('https://example.org/notice-constraint'), iri('http://www.w3.org/ns/odrl/2/rightOperand'), literal('3', datatype('http://www.w3.org/2001/XMLSchema#string')), default_graph).
rdf(iri('https://example.org/share-data'), iri('https://example.org/clause'), literal('c3', datatype('http://www.w3.org/2001/XMLSchema#string')), default_graph).
rdf(iri('https://example.org/share-data'), iri('http://www.w3.org/ns/odrl/2/action'), iri('https://example.org/disclose'), default_graph).
rdf(iri('https://example.org/export-data'), iri('https://example.org/clause'), literal('c4', datatype('http://www.w3.org/2001/XMLSchema#string')), default_graph).
rdf(iri('https://example.org/export-data'), iri('http://www.w3.org/ns/odrl/2/action'), iri('https://example.org/export'), default_graph).
rdf(iri('https://example.org/deletion-profile'), iri('https://example.org/risk'), iri('https://example.org/deletion-risk'), default_graph).
rdf(iri('https://example.org/deletion-profile'), iri('https://example.org/policyRule'), iri('https://example.org/delete-account'), default_graph).
rdf(iri('https://example.org/deletion-profile'), iri('https://example.org/need'), iri('https://example.org/no-deletion-without-notice'), default_graph).
rdf(iri('https://example.org/deletion-profile'), iri('https://example.org/baseScore'), literal('90', datatype('http://www.w3.org/2001/XMLSchema#string')), default_graph).
rdf(iri('https://example.org/deletion-profile'), iri('https://example.org/mitigation'), iri('https://example.org/require-notice-before-deletion'), default_graph).
rdf(iri('https://example.org/terms-profile'), iri('https://example.org/risk'), iri('https://example.org/terms-risk'), default_graph).
rdf(iri('https://example.org/terms-profile'), iri('https://example.org/policyRule'), iri('https://example.org/change-terms'), default_graph).
rdf(iri('https://example.org/terms-profile'), iri('https://example.org/need'), iri('https://example.org/change-only-with-14-days-notice'), default_graph).
rdf(iri('https://example.org/terms-profile'), iri('https://example.org/baseScore'), literal('70', datatype('http://www.w3.org/2001/XMLSchema#string')), default_graph).
rdf(iri('https://example.org/terms-profile'), iri('https://example.org/mitigation'), iri('https://example.org/require-14-days-notice'), default_graph).
rdf(iri('https://example.org/sharing-profile'), iri('https://example.org/risk'), iri('https://example.org/sharing-risk'), default_graph).
rdf(iri('https://example.org/sharing-profile'), iri('https://example.org/policyRule'), iri('https://example.org/share-data'), default_graph).
rdf(iri('https://example.org/sharing-profile'), iri('https://example.org/need'), iri('https://example.org/no-sharing-without-consent'), default_graph).
rdf(iri('https://example.org/sharing-profile'), iri('https://example.org/baseScore'), literal('85', datatype('http://www.w3.org/2001/XMLSchema#string')), default_graph).
rdf(iri('https://example.org/sharing-profile'), iri('https://example.org/mitigation'), iri('https://example.org/require-explicit-consent'), default_graph).
rdf(iri('https://example.org/portability-profile'), iri('https://example.org/risk'), iri('https://example.org/portability-risk'), default_graph).
rdf(iri('https://example.org/portability-profile'), iri('https://example.org/policyRule'), iri('https://example.org/export-data'), default_graph).
rdf(iri('https://example.org/portability-profile'), iri('https://example.org/need'), iri('https://example.org/data-portability'), default_graph).
rdf(iri('https://example.org/portability-profile'), iri('https://example.org/baseScore'), literal('60', datatype('http://www.w3.org/2001/XMLSchema#string')), default_graph).
rdf(iri('https://example.org/portability-profile'), iri('https://example.org/mitigation'), iri('https://example.org/permit-data-export'), default_graph).
rdf(iri('https://example.org/no-deletion-without-notice'), iri('https://example.org/importance'), literal('20', datatype('http://www.w3.org/2001/XMLSchema#string')), default_graph).
rdf(iri('https://example.org/change-only-with-14-days-notice'), iri('https://example.org/importance'), literal('15', datatype('http://www.w3.org/2001/XMLSchema#string')), default_graph).
rdf(iri('https://example.org/change-only-with-14-days-notice'), iri('https://example.org/minimumNoticeDays'), literal('14', datatype('http://www.w3.org/2001/XMLSchema#string')), default_graph).
rdf(iri('https://example.org/no-sharing-without-consent'), iri('https://example.org/importance'), literal('12', datatype('http://www.w3.org/2001/XMLSchema#string')), default_graph).
rdf(iri('https://example.org/data-portability'), iri('https://example.org/importance'), literal('10', datatype('http://www.w3.org/2001/XMLSchema#string')), default_graph).
