% Generated by rdf-prolog-roundtrip.

% RDF terms use rdf(Subject, Predicate, Object, Graph).

rdf(iri('https://example.org/advanced-policy'), iri('http://www.w3.org/ns/odrl/2/permission'), iri('https://example.org/research-permission'), default_graph).
rdf(iri('https://example.org/advanced-policy'), iri('http://www.w3.org/ns/odrl/2/prohibition'), iri('https://example.org/transfer-prohibition'), default_graph).
rdf(iri('https://example.org/research-permission'), iri('http://www.w3.org/ns/odrl/2/target'), iri('https://example.org/health-dataset'), default_graph).
rdf(iri('https://example.org/research-permission'), iri('http://www.w3.org/ns/odrl/2/action'), iri('http://www.w3.org/ns/odrl/2/use'), default_graph).
rdf(iri('https://example.org/research-permission'), iri('http://www.w3.org/ns/odrl/2/assignee'), iri('https://example.org/research-hospital'), default_graph).
rdf(iri('https://example.org/research-permission'), iri('http://www.w3.org/ns/odrl/2/constraint'), iri('https://example.org/purpose-constraint'), default_graph).
rdf(iri('https://example.org/research-permission'), iri('http://www.w3.org/ns/odrl/2/constraint'), iri('https://example.org/region-constraint'), default_graph).
rdf(iri('https://example.org/research-permission'), iri('http://www.w3.org/ns/odrl/2/duty'), iri('https://example.org/deidentify-duty'), default_graph).
rdf(iri('https://example.org/purpose-constraint'), iri('http://www.w3.org/ns/odrl/2/leftOperand'), iri('http://www.w3.org/ns/odrl/2/purpose'), default_graph).
rdf(iri('https://example.org/purpose-constraint'), iri('http://www.w3.org/ns/odrl/2/operator'), iri('http://www.w3.org/ns/odrl/2/eq'), default_graph).
rdf(iri('https://example.org/purpose-constraint'), iri('http://www.w3.org/ns/odrl/2/rightOperand'), iri('https://example.org/medical-research'), default_graph).
rdf(iri('https://example.org/region-constraint'), iri('http://www.w3.org/ns/odrl/2/leftOperand'), iri('http://www.w3.org/ns/odrl/2/spatial'), default_graph).
rdf(iri('https://example.org/region-constraint'), iri('http://www.w3.org/ns/odrl/2/operator'), iri('http://www.w3.org/ns/odrl/2/eq'), default_graph).
rdf(iri('https://example.org/region-constraint'), iri('http://www.w3.org/ns/odrl/2/rightOperand'), iri('https://example.org/eu'), default_graph).
rdf(iri('https://example.org/deidentify-duty'), iri('http://www.w3.org/ns/odrl/2/action'), iri('https://example.org/deidentify'), default_graph).
rdf(iri('https://example.org/transfer-prohibition'), iri('http://www.w3.org/ns/odrl/2/target'), iri('https://example.org/health-dataset'), default_graph).
rdf(iri('https://example.org/transfer-prohibition'), iri('http://www.w3.org/ns/odrl/2/action'), iri('http://www.w3.org/ns/odrl/2/transfer'), default_graph).
rdf(iri('https://example.org/transfer-prohibition'), iri('http://www.w3.org/ns/odrl/2/assignee'), iri('https://example.org/research-hospital'), default_graph).
