% Generated by rdf-prolog-roundtrip.

% RDF terms use rdf(Subject, Predicate, Object, Graph).

rdf(iri('https://example.org/trust-policy'), iri('http://www.w3.org/ns/odrl/2/permission'), iri('https://example.org/healthcare-permission'), default_graph).
rdf(iri('https://example.org/trust-policy'), iri('http://www.w3.org/ns/odrl/2/prohibition'), iri('https://example.org/marketing-prohibition'), default_graph).
rdf(iri('https://example.org/healthcare-permission'), iri('http://www.w3.org/ns/odrl/2/assignee'), iri('https://example.org/research-partner'), default_graph).
rdf(iri('https://example.org/healthcare-permission'), iri('http://www.w3.org/ns/odrl/2/target'), iri('https://example.org/lab-result'), default_graph).
rdf(iri('https://example.org/healthcare-permission'), iri('http://www.w3.org/ns/odrl/2/action'), iri('http://www.w3.org/ns/odrl/2/use'), default_graph).
rdf(iri('https://example.org/healthcare-permission'), iri('http://www.w3.org/ns/odrl/2/purpose'), iri('https://example.org/healthcare'), default_graph).
rdf(iri('https://example.org/healthcare-permission'), iri('https://example.org/minTrust'), literal('0.80', datatype('http://www.w3.org/2001/XMLSchema#string')), default_graph).
rdf(iri('https://example.org/marketing-prohibition'), iri('http://www.w3.org/ns/odrl/2/assignee'), iri('https://example.org/ad-network'), default_graph).
rdf(iri('https://example.org/marketing-prohibition'), iri('http://www.w3.org/ns/odrl/2/target'), iri('https://example.org/lab-result'), default_graph).
rdf(iri('https://example.org/marketing-prohibition'), iri('http://www.w3.org/ns/odrl/2/action'), iri('http://www.w3.org/ns/odrl/2/distribute'), default_graph).
rdf(iri('https://example.org/marketing-prohibition'), iri('http://www.w3.org/ns/odrl/2/purpose'), iri('https://example.org/marketing'), default_graph).
rdf(iri('https://example.org/hospital-a'), iri('https://example.org/trustScore'), literal('0.92', datatype('http://www.w3.org/2001/XMLSchema#string')), default_graph).
rdf(iri('https://example.org/small-clinic'), iri('https://example.org/trustScore'), literal('0.63', datatype('http://www.w3.org/2001/XMLSchema#string')), default_graph).
rdf(iri('https://example.org/ad-network'), iri('https://example.org/trustScore'), literal('0.28', datatype('http://www.w3.org/2001/XMLSchema#string')), default_graph).
rdf(iri('https://example.org/flow-care'), iri('https://example.org/source'), iri('https://example.org/hospital-a'), default_graph).
rdf(iri('https://example.org/flow-care'), iri('https://example.org/recipient'), iri('https://example.org/research-partner'), default_graph).
rdf(iri('https://example.org/flow-care'), iri('https://example.org/data'), iri('https://example.org/lab-result'), default_graph).
rdf(iri('https://example.org/flow-care'), iri('https://example.org/requestedAction'), iri('http://www.w3.org/ns/odrl/2/use'), default_graph).
rdf(iri('https://example.org/flow-care'), iri('https://example.org/requestedPurpose'), iri('https://example.org/healthcare'), default_graph).
rdf(iri('https://example.org/flow-clinic'), iri('https://example.org/source'), iri('https://example.org/small-clinic'), default_graph).
rdf(iri('https://example.org/flow-clinic'), iri('https://example.org/recipient'), iri('https://example.org/research-partner'), default_graph).
rdf(iri('https://example.org/flow-clinic'), iri('https://example.org/data'), iri('https://example.org/lab-result'), default_graph).
rdf(iri('https://example.org/flow-clinic'), iri('https://example.org/requestedAction'), iri('http://www.w3.org/ns/odrl/2/use'), default_graph).
rdf(iri('https://example.org/flow-clinic'), iri('https://example.org/requestedPurpose'), iri('https://example.org/healthcare'), default_graph).
rdf(iri('https://example.org/flow-ads'), iri('https://example.org/source'), iri('https://example.org/hospital-a'), default_graph).
rdf(iri('https://example.org/flow-ads'), iri('https://example.org/recipient'), iri('https://example.org/ad-network'), default_graph).
rdf(iri('https://example.org/flow-ads'), iri('https://example.org/data'), iri('https://example.org/lab-result'), default_graph).
rdf(iri('https://example.org/flow-ads'), iri('https://example.org/requestedAction'), iri('http://www.w3.org/ns/odrl/2/distribute'), default_graph).
rdf(iri('https://example.org/flow-ads'), iri('https://example.org/requestedPurpose'), iri('https://example.org/marketing'), default_graph).
