% Generated by rdf-prolog-roundtrip.

% RDF terms use rdf(Subject, Predicate, Object, Graph).

rdf(iri('https://example.org/healthcare-policy'), iri('http://www.w3.org/ns/odrl/2/permission'), iri('https://example.org/research-use'), default_graph).
rdf(iri('https://example.org/healthcare-policy'), iri('http://www.w3.org/ns/odrl/2/permission'), iri('https://example.org/genomic-sharing'), default_graph).
rdf(iri('https://example.org/healthcare-policy'), iri('http://www.w3.org/ns/odrl/2/permission'), iri('https://example.org/record-retention'), default_graph).
rdf(iri('https://example.org/healthcare-policy'), iri('https://example.org/riskProfile'), iri('https://example.org/consent-profile'), default_graph).
rdf(iri('https://example.org/healthcare-policy'), iri('https://example.org/riskProfile'), iri('https://example.org/sharing-profile'), default_graph).
rdf(iri('https://example.org/healthcare-policy'), iri('https://example.org/riskProfile'), iri('https://example.org/retention-profile'), default_graph).
rdf(iri('https://example.org/research-use'), iri('https://example.org/clause'), literal('h1', datatype('http://www.w3.org/2001/XMLSchema#string')), default_graph).
rdf(iri('https://example.org/research-use'), iri('http://www.w3.org/ns/odrl/2/action'), iri('http://www.w3.org/ns/odrl/2/use'), default_graph).
rdf(iri('https://example.org/genomic-sharing'), iri('https://example.org/clause'), literal('h2', datatype('http://www.w3.org/2001/XMLSchema#string')), default_graph).
rdf(iri('https://example.org/genomic-sharing'), iri('http://www.w3.org/ns/odrl/2/action'), iri('https://example.org/disclose'), default_graph).
rdf(iri('https://example.org/genomic-sharing'), iri('http://www.w3.org/ns/odrl/2/target'), iri('https://example.org/genomic-data'), default_graph).
rdf(iri('https://example.org/record-retention'), iri('https://example.org/clause'), literal('h4', datatype('http://www.w3.org/2001/XMLSchema#string')), default_graph).
rdf(iri('https://example.org/record-retention'), iri('http://www.w3.org/ns/odrl/2/constraint'), iri('https://example.org/retention-constraint'), default_graph).
rdf(iri('https://example.org/retention-constraint'), iri('http://www.w3.org/ns/odrl/2/leftOperand'), iri('https://example.org/retentionDays'), default_graph).
rdf(iri('https://example.org/retention-constraint'), iri('http://www.w3.org/ns/odrl/2/operator'), iri('http://www.w3.org/ns/odrl/2/eq'), default_graph).
rdf(iri('https://example.org/retention-constraint'), iri('http://www.w3.org/ns/odrl/2/rightOperand'), literal('3650', datatype('http://www.w3.org/2001/XMLSchema#string')), default_graph).
rdf(iri('https://example.org/consent-profile'), iri('https://example.org/risk'), iri('https://example.org/consent-risk'), default_graph).
rdf(iri('https://example.org/consent-profile'), iri('https://example.org/policyRule'), iri('https://example.org/research-use'), default_graph).
rdf(iri('https://example.org/consent-profile'), iri('https://example.org/need'), iri('https://example.org/explicit-consent-for-research'), default_graph).
rdf(iri('https://example.org/consent-profile'), iri('https://example.org/baseScore'), literal('85', datatype('http://www.w3.org/2001/XMLSchema#string')), default_graph).
rdf(iri('https://example.org/consent-profile'), iri('https://example.org/mitigation'), iri('https://example.org/require-explicit-consent'), default_graph).
rdf(iri('https://example.org/sharing-profile'), iri('https://example.org/risk'), iri('https://example.org/sharing-risk'), default_graph).
rdf(iri('https://example.org/sharing-profile'), iri('https://example.org/policyRule'), iri('https://example.org/genomic-sharing'), default_graph).
rdf(iri('https://example.org/sharing-profile'), iri('https://example.org/need'), iri('https://example.org/deidentify-before-sharing'), default_graph).
rdf(iri('https://example.org/sharing-profile'), iri('https://example.org/baseScore'), literal('90', datatype('http://www.w3.org/2001/XMLSchema#string')), default_graph).
rdf(iri('https://example.org/sharing-profile'), iri('https://example.org/mitigation'), iri('https://example.org/require-deidentification'), default_graph).
rdf(iri('https://example.org/retention-profile'), iri('https://example.org/risk'), iri('https://example.org/retention-risk'), default_graph).
rdf(iri('https://example.org/retention-profile'), iri('https://example.org/policyRule'), iri('https://example.org/record-retention'), default_graph).
rdf(iri('https://example.org/retention-profile'), iri('https://example.org/need'), iri('https://example.org/retention-limit-3-years'), default_graph).
rdf(iri('https://example.org/retention-profile'), iri('https://example.org/baseScore'), literal('55', datatype('http://www.w3.org/2001/XMLSchema#string')), default_graph).
rdf(iri('https://example.org/retention-profile'), iri('https://example.org/mitigation'), iri('https://example.org/limit-retention-to-1095-days'), default_graph).
rdf(iri('https://example.org/explicit-consent-for-research'), iri('https://example.org/importance'), literal('35', datatype('http://www.w3.org/2001/XMLSchema#string')), default_graph).
rdf(iri('https://example.org/deidentify-before-sharing'), iri('https://example.org/importance'), literal('35', datatype('http://www.w3.org/2001/XMLSchema#string')), default_graph).
rdf(iri('https://example.org/retention-limit-3-years'), iri('https://example.org/importance'), literal('15', datatype('http://www.w3.org/2001/XMLSchema#string')), default_graph).
rdf(iri('https://example.org/retention-limit-3-years'), iri('https://example.org/maximumDays'), literal('1095', datatype('http://www.w3.org/2001/XMLSchema#string')), default_graph).
